### ISSUE TITLE
Field name is not displayed for coded questions with multiple answers

### ISSUE THREAD

**Issue by cioan** [PIH/openmrs-module-pihcore#479]
@mogoodrich , the following line of code never worked because the index does not refer to an ordered array with only fields with values, but rather to all the coded answers for that obs and in not in order:
https://github.com/PIH/openmrs-module-pihcore/blame/0acb317ccffcd2866671e6d042a0fb029b829d14/omod/src/main/webapp/pages/visit/templates/encounters/defaultHtmlFormEncounterLong.gsp#L18

    <span ng-repeat="section in templateModel.sections" class="aligned">
        <span ng-repeat="field in section.fields" class="aligned">
            <p ng-show="field.value" class="aligned">
                
                
                <label>{{ (\$index == 0 || field.name != section.fields[\$index-1].name) ? field.name : '' }}</label>
                <span class="obs-value">{{ field.value }}</span>
            </p>
            <span ng-repeat="childField in field.fields" class="aligned">
                <p ng-show="childField.value" class="aligned">
                    <label>{{ (\$index == 0 || childField.name != field.fields[\$index-1].name) ? childField.name : '' }}</label>
                    <span class="obs-value">{{ childField.value }}</span>
                </p>
            </span>
        </span>
    </span>

Here is how it looks now, and I was trying to figure out why the label for the coded question does not display:
![Screenshot 2024-02-20 at 8 41 49 AM](https://github.com/PIH/openmrs-module-pihcore/assets/1633285/acaab54d-9076-4f10-84ba-db342e5b27aa)

so, I added a little debug code to understand what happens:
![Screenshot 2024-02-20 at 8 58 24 AM](https://github.com/PIH/openmrs-module-pihcore/assets/1633285/4fbf1050-0470-49e4-ae33-dcb1c944f4ea)

Here is the coded question, **_Reason for referral:_** with the multiple answers in the edit mode:
![Screenshot 2024-02-20 at 8 43 39 AM](https://github.com/PIH/openmrs-module-pihcore/assets/1633285/8c2a9a4f-a443-4d03-b294-39317b681d50)

**Comment by mogoodrich** [comment]
Ugh, yeah, thanks @cioan, nice catch...  it looks like if there are multiple fields with the same label, the assumption in the code is that the first field has a value.

What if we change that expression so that it also checks that  section.fields[\$index-1].value != null?

It wouldn't be perfect, because in the above example since "Pain" and "Bleeding" are not next to each other it would display the label twice, I believe, but that's probably better than not at all.  Or we could lobby with the team for just removing this functionality entirely and displaying the labels multiple times in all cases.  

Or if you got another idea, lmk!

**Comment by mseaton** [comment]
@cioan - you addressed this right?  Can we close this issue?  (not sure why this is in github issues, but we should clean it up if done)

**Comment by cioan** [comment]
This issue has been addressed in this PR: 
https://github.com/PIH/openmrs-module-pihcore/pull/480
